;; -*- mode:lisp -*-

(package "helm-swoop"
         "3.0.0"
         "Efficiently hopping squeezed lines powered by helm interface")

(package-file "helm-swoop.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "25.1")
(depends-on "helm")

(development
 (depends-on "buttercup"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
